version: '3'

services:
  flask-app:
    build: .  # Build the image from the dockerfile in the current directory
    image: hanine169/first-flask-app:latest  # Specify the name of the image
    volumes: 
      - my-app-data:/app/data  # command the host to create folder myapp data to mount it to /app/data that stores the dataof the container
    ports:
      - "5000:5000" 
    environment:  # Environment variables (if needed)
      - FLASK_ENV=development #example
    networks:
      - my-network #to connect to a custom network 

volumes:
  my-app-data:  # Define the volume
networks:
  my-network:  # Define a custom network (optional)
